import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { SocketInitializer } from "../components/SocketInitializer";
import { ClientAuthHandlerShell } from "./ClientAuthHandlerShell";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  //we fetch the user status here and set the state in the store
  let userLoginStatus;
  let user;
  try {
    //SSR, cuz cache: 'no-store'
    const res = await fetch('/api/v1/auth/me', {
      credentials: "include",
      cache: 'no-store'
    })
    if (res.ok) {
      const resData = await res.json();
      console.log("User Login Data full object: ", resData)
      userLoginStatus = resData.isAuthenticated;
      user = resData.user
    } else {
      userLoginStatus = false
    }
  } catch (err) {
    userLoginStatus = false;
    //toaster: error
  }


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <StoreProvider>
          <ClientAuthHandlerShell isLoggedIn={userLoginStatus} userId={user?.id} email={user?.email}>
            <SocketInitializer />
            {children}
          </ClientAuthHandlerShell>
        </StoreProvider>

      </body>
    </html>
  );
}
