import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { SocketInitializer } from "../components/SocketInitializer";
import { ClientAuthHandlerShell } from "./ClientAuthHandlerShell";
import { Toaster } from "sonner";
import { cookies } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  //we fetch the user status here and set the state in the store
  let userLoginStatus;
  let user;
  try {
    const cookieStore = await cookies();
    //SSR, cuz cache: 'no-store'
    const res = await fetch('http://localhost:8000/api/v1/auth/me', {
      headers: {
        Cookie: cookieStore.toString()
      },
      cache: 'no-store'
    })
    const resData = await res.json();
    console.log("User Login Data full object: ", resData);

    if (res.ok) {
      userLoginStatus = resData.isAuthenticated;
      user = resData.user
    } else {
      userLoginStatus = false
      console.log("User is not logged in.");
    }

  } catch (err) {
    userLoginStatus = false;
    //toaster: error
    console.log("Error while fetching user login status: ", err);
  }


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <StoreProvider>
          <ClientAuthHandlerShell isLoggedIn={userLoginStatus} userId={user?.id} email={user?.email}>
            <SocketInitializer />
            {children}
            <Toaster
              position="bottom-right"
              theme="dark"
              toastOptions={{
                style: {
                  background: 'rgba(10, 10, 10, 0.95)',
                  border: '1px solid rgba(255, 255, 255, 0.1)',
                  backdropFilter: 'blur(20px)',
                  color: '#fff',
                },
                classNames: {
                  success: 'border-rose-500/30 bg-gradient-to-r from-rose-500/10 to-transparent',
                  error: 'border-red-500/30 bg-gradient-to-r from-red-500/10 to-transparent',
                },
              }}
            />
          </ClientAuthHandlerShell>
        </StoreProvider>

      </body>
    </html>
  );
}
